### ISSUE TITLE
There is a lot of noise in Learn browser console

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#3] opened 2016-06-29 00:53 UTC
I know this is not the right place for this, but just gonna start it off in here and it can be moved as is.

The JS course asks the students to type a lot into the browser during the course it seems (or at least in the intro) and it looks like the Learn console is pretty noisy. 

![screen shot 2016-06-28 at 8 49 59 pm](https://cloud.githubusercontent.com/assets/13033515/16437122/13e4e012-3d72-11e6-8304-24712194f5d9.png)

As I try and type and follow along, chats going to other channels keep popping up. Not sure if my account is in some sort of dev mode or if students will see this, but can this be shut off for students?

@pletcher @edwardgaudio @joshrowley @AnnJohn

**Comment by pletcher** [comment] 2016-06-29 00:53
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment] 2016-06-29 13:20
That's true. We also tend to leak private keys and stuff in console, which is a little worrisome.

I'll echo @aturkewi's question: are we only seeing these logs because of our account's permissions, or are they something that everyone sees?

**Comment by joshrowley** [comment] 2016-06-29 15:09
@pletcher @aturkewi 

Hey @aturkewi those chat messages are showing up for everybody, we can/should remove those consoles, or at least set it to show up only at a "debug" log level.

@pletcher i'll follow up with you

**Comment by pletcher** [comment] 2016-06-30 20:45
@joshrowley is there an open issue we can track on Ironboard?

**Comment by joshrowley** [comment] 2016-07-01 17:53
@pletcher @aturkewi both issues should be fixed / @aturkewi lmk if there's any other garbage logging to console

**Closed by joshrowley** 2016-07-01 17:53 UTC
